header_color:
  type: string
  default: "255, 255, 255"
  description: "RGB color code, e.g.: 47, 79, 79 <br> Or you can use RGB color variables, e.g.: var(--header_background-rgb)"
header_transparency:
  type: string
  default: "1"
  description: "Transparency, for example: 0.8"
