header_color:
  type: string
  default: "255, 255, 255"
  description: "rgb color code, for example: 47, 79, 79"
header_transparency:
  type: string
  default: "1"
  description: "Transparency, for example: 0.8"
